### PR TITLE
Level added

### PR DESCRIPTION
**Pull request by Darkknight0125**
Issue: #17

Created a scene with level 1.

Screenshot (288)
Screenshot (287)

### CODE REVIEW

**Comment by Gamin8ing** [comment]
hey @Darkknight0125 please add screenshots of your level

**Comment by Darkknight0125** [comment]
@Gamin8ing  Added the screenshots. Please review

**Comment by Gamin8ing** [comment]
@Darkknight0125 please add `.vscode` folder to the `.gitignore` file, and also, if you can, colour the obstacles, you may the material from the `Material` folder.

thank you

**Comment by Darkknight0125** [comment]
@Gamin8ing  Colored the level and removed the .vscode, the commit shows some changes to project settings, i did not do them, i hope its normal, otherwise let me know and ill recreate the level from scratch.

**Comment by Gamin8ing** [comment]
@Darkknight0125 no problem, i have looked and merging the PR

**Pull request merged**
